### PR TITLE
Provide an option to use single-part High Vis buttons for the Jog2K Deluxe version instead of 2-part buttons

### PR DESCRIPTION
**Pull request by R-Ronald**
Currently the Deluxe version of the Jog2K uses 9 buttons that are printed in white with black button caps (along with many other buttons that are not relevant to this request).

I have an alternative set of buttons that use icons designed to be "colored in" using a dark Ultra Fine Point Sharpie. The buttons are simpler and less difficult to print, don't require assembly, and provide better contrast/legibility. See the readme.pdf file in the forked version for a picture of what these buttons look like.

I have 6 STL files for 3d printing the 9 required buttons. I also have a readme.txt that provides instructions for substituting these buttons for the baseline version and a readme.pdf that includes a picture. All 8 of these files are provided in a single sub- directory with the name of "SimplifiedHighVis" alongside the White, Black and Clear sub-directories.

### CODE REVIEW

**Comment by mikemacwillie** [comment]
Thanks for submitting these! Apologies for the delay here; we've been working on tidying up the 3D printed parts for all of the projects over the last few days by migrating them to a new repository. Would you mind if I migrate these over to the new [Mods & Accessories](https://github.com/Expatria-Technologies/Mods-Accessories/) repository? Or would you prefer to submit a PR over there?

**Comment by R-Ronald** [comment]
Mike,

No problem on the wait. I already have my mods in place. 😁

My buttons pair with the other Deluxe version ones (I only replace about 
a third of them), so I think they should stay near to each other. But if 
they are all headed over, you can certainly move mine too.

Thanks for putting up with all of us and for trying to bring order from 
the chaos!

RR

**Comment by mikemacwillie** [comment]
Great, we will get them migrated over. Thanks for including the readme data too, that is a huge help!

**Comment by mikemacwillie** [comment]
Migrated to [Mods & Accessories](https://github.com/Expatria-Technologies/Mods-Accessories/) .

**Pull request closed without merging**
